// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Q4hVpuettHppOUTTHkWgG9Ef6UW3ggc',
    appId: '1:575711175949:web:c5d6e22fc8cb9986da7c44',
    messagingSenderId: '575711175949',
    projectId: 'trini-flutter-project',
    authDomain: 'trini-flutter-project.firebaseapp.com',
    storageBucket: 'trini-flutter-project.appspot.com',
    measurementId: 'G-7ZJQ7PW65H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpHMFVXIyEsKW0RyAJlb5WbGJoMmqXinQ',
    appId: '1:575711175949:android:aecfdb1bcb22e2c6da7c44',
    messagingSenderId: '575711175949',
    projectId: 'trini-flutter-project',
    storageBucket: 'trini-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG62W3Bj4KffvTcChE0bfikbUt2o0BWtE',
    appId: '1:575711175949:ios:6f7a96d44593bc76da7c44',
    messagingSenderId: '575711175949',
    projectId: 'trini-flutter-project',
    storageBucket: 'trini-flutter-project.appspot.com',
    iosClientId: '575711175949-fnnp613pva30ugdq8m13udvfk778lrtq.apps.googleusercontent.com',
    iosBundleId: 'com.trini.trini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG62W3Bj4KffvTcChE0bfikbUt2o0BWtE',
    appId: '1:575711175949:ios:2a9322f2e28797d3da7c44',
    messagingSenderId: '575711175949',
    projectId: 'trini-flutter-project',
    storageBucket: 'trini-flutter-project.appspot.com',
    iosClientId: '575711175949-0if5rjakgtp08djbl6ndpr1opgl044m5.apps.googleusercontent.com',
    iosBundleId: 'com.trini.trini.RunnerTests',
  );
}
