import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:trini/services/cloud/cloud_storage_constants.dart';
import 'package:flutter/foundation.dart';

@immutable
class CloudWorkout {
  // this a primary ket generated by firebase
  final String documentId;
  final String ownerUserId;
  final String text;
  final String sets;
  const CloudWorkout({
    required this.documentId,
    required this.ownerUserId,
    required this.text,
    // I added this
    required this.sets,
  });

  CloudWorkout.fromSnapshot(
      QueryDocumentSnapshot<Map<String, dynamic>> snapshot)
      : documentId = snapshot.id,
        ownerUserId = snapshot.data()[ownerUserIdFieldName],
        text = snapshot.data()[textFieldName] as String,
        // I added this
        sets = snapshot.data()[setsFieldName] as String;
}
